apiVersion: 1
datasources:
  - name: RACEPULSE MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: racepulse
    user: racepulse_user
    secureJsonData:
      password: racepulse_pass
    isDefault: true
    editable: true